const canvas=document.querySelector('#game');
const ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id);
window.addEventListener('error',e=>console.error('RogueGame:',e.error||e.message));let W,H,dpr,state='menu',player,enemies=[],bullets=[],drops=[],particles=[],keys={},mouse={x:0,y:0},elapsed=0,spawn=0,last=0;
const upgrades=[['锋利武器','攻击伤害 +25%',p=>p.damage*=1.25],['迅捷','移动速度 +18%',p=>p.speed*=1.18],['生命强化','最大生命 +30，并回复 30',p=>{p.maxHp+=30;p.hp=Math.min(p.maxHp,p.hp+30)}],['多重射击','同时发射更多子弹',p=>p.multishot=Math.min(5,p.multishot+1)],['攻击速度','攻击间隔 -18%',p=>p.fireRate=Math.max(.12,p.fireRate*.82)],['磁力','拾取范围 +50%',p=>p.magnet*=1.5]];
function resize(){dpr=devicePixelRatio||1;W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);canvas.addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});canvas.addEventListener('pointerdown',e=>{mouse.x=e.clientX;mouse.y=e.clientY});
$('start').onclick=()=>start();$('again').onclick=()=>start();$('continue').onclick=loadCloud;$('save').onclick=()=>saveCloud(true);
function start(data){elapsed=0;spawn=0;enemies=[];bullets=[];drops=[];particles=[];player={x:W/2,y:H/2,r:15,hp:100,maxHp:100,speed:230,damage:18,fireRate:.45,fire:0,multishot:1,magnet:80,level:1,xp:0,next:10,gold:0,kills:0};if(data)Object.assign(player,data);state='playing';hide('menu');hide('result');hide('levelup');last=performance.now();requestAnimationFrame(loop)}
function hide(id){$(id).classList.add('hidden')}function show(id){$(id).classList.remove('hidden')}
function loop(t){if(state!=='playing')return;const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}
function update(dt){elapsed+=dt;spawn-=dt;player.fire-=dt;let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(dx,dy)||1;player.x=Math.max(20,Math.min(W-20,player.x+dx/l*player.speed*dt));player.y=Math.max(20,Math.min(H-20,player.y+dy/l*player.speed*dt));if(spawn<=0){spawn=Math.max(.22,1-elapsed/300);spawnEnemy()}if(player.fire<=0){shoot();player.fire=player.fireRate}
for(const e of enemies){let a=Math.atan2(player.y-e.y,player.x-e.x);e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;if(dist(e,player)<e.r+player.r){player.hp-=e.dmg*dt;if(player.hp<=0){end();return}}}
for(const b of bullets){b.x+=Math.cos(b.a)*b.speed*dt;b.y+=Math.sin(b.a)*b.speed*dt;b.life-=dt;for(const e of enemies)if(!e.dead&&dist(b,e)<b.r+e.r){e.hp-=b.damage;b.life=0;if(e.hp<=0)kill(e)}}bullets=bullets.filter(b=>b.life>0&&b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);enemies=enemies.filter(e=>!e.dead);
for(const d of drops){let dd=dist(d,player);if(dd<player.magnet){let a=Math.atan2(player.y-d.y,player.x-d.x);d.x+=Math.cos(a)*180*dt;d.y+=Math.sin(a)*180*dt}if(dist(d,player)<player.r+d.r){if(d.type==='xp')gainXp(d.v);else player.gold+=d.v;d.dead=true}}drops=drops.filter(d=>!d.dead);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);ui()}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function spawnEnemy(){let s=Math.floor(Math.random()*4),x=s<2?(s?W+30:-30):Math.random()*W,y=s<2?Math.random()*H:(s===2?-30:H+30),elite=Math.random()<Math.min(.18,elapsed/500),hp=elite?75+elapsed*.5:28+elapsed*.18;enemies.push({x,y,r:elite?20:13,hp,maxHp:hp,speed:elite?55:75+Math.min(45,elapsed*.05),dmg:elite?22:12,elite,dead:false})}
function shoot(){if(!enemies.length)return;let t=enemies.reduce((a,e)=>dist(e,player)<dist(a,player)?e:a,enemies[0]),base=Math.atan2(t.y-player.y,t.x-player.x);for(let i=0;i<player.multishot;i++){let spread=(i-(player.multishot-1)/2)*.12;bullets.push({x:player.x,y:player.y,a:base+spread,speed:600,r:5,damage:player.damage,life:1.2})}}
function kill(e){e.dead=true;player.kills++;drops.push({x:e.x,y:e.y,r:6,type:'xp',v:e.elite?5:2});if(Math.random()<.12)drops.push({x:e.x+5,y:e.y+5,r:5,type:'gold',v:e.elite?5:1});for(let i=0;i<5;i++)particles.push({x:e.x,y:e.y,vx:(Math.random()-.5)*120,vy:(Math.random()-.5)*120,life:.3})}
function gainXp(v){player.xp+=v;if(player.xp>=player.next){player.xp-=player.next;player.level++;player.next=Math.floor(player.next*1.35);state='levelup';$('choices').innerHTML='';[...upgrades].sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{let el=document.createElement('div');el.className='choice';el.innerHTML='<strong>'+u[0]+'</strong><span>'+u[1]+'</span>';el.onclick=()=>{u[2](player);hide('levelup');state='playing';last=performance.now();requestAnimationFrame(loop)};$('choices').appendChild(el)});show('levelup')}}
function end(){state='result';$('resultTitle').textContent='你倒下了';$('resultText').textContent='等级 '+player.level+' · 击杀 '+player.kills+' · 金币 '+player.gold+' · 生存 '+fmt(elapsed);show('result');saveCloud(false)}
function fmt(s){return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function ui(){$('hp').textContent=Math.ceil(player.hp)+'/'+player.maxHp;$('level').textContent=player.level;$('gold').textContent=player.gold;$('time').textContent=fmt(elapsed);$('hpbar').style.width=Math.max(0,player.hp/player.maxHp*100)+'%';$('xpbar').style.width=Math.min(100,player.xp/player.next*100)+'%'}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b0e14';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#161c26';for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const d of drops){ctx.fillStyle=d.type==='xp'?'#63a4ff':'#ffd45c';ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,7);ctx.fill()}for(const b of bullets){ctx.fillStyle='#ffe08a';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()}for(const e of enemies){ctx.fillStyle=e.elite?'#c66cff':'#e85d75';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,7);ctx.fill()}ctx.fillStyle='#70a1ff';ctx.beginPath();ctx.arc(player.x,player.y,player.r,0,7);ctx.fill();let a=Math.atan2(mouse.y-player.y,mouse.x-player.x);ctx.strokeStyle='#dbe7ff';ctx.beginPath();ctx.moveTo(player.x,player.y);ctx.lineTo(player.x+Math.cos(a)*25,player.y+Math.sin(a)*25);ctx.stroke();for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/.3);ctx.fillStyle='#fff';ctx.fillRect(p.x,p.y,3,3)}ctx.globalAlpha=1}
async function saveCloud(manual){try{let r=await fetch('/api/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({player,elapsed})});if(!r.ok)throw Error();if(manual)toast('云存档已保存')}catch(e){if(manual)toast('云存档不可用，本地仍可游玩')}}
async function loadCloud(){try{let r=await fetch('/api/save');if(!r.ok)throw Error();let d=await r.json();if(d.save){start(d.save.player);toast('已读取云存档')}else toast('暂无云存档')}catch(e){toast('暂无可用云存档')}}
function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;setTimeout(()=>$('toast').style.opacity=0,1600)}
